F/training 55
Ammar022/go-training pull request #1
Opened 2023-02-01 07:49 UTC by Ammar022

- Added functionality to read and parse .csv files given as command line argument. 
- Added functionality to print data in JSON Format.
- Updated README.md.

2023-02-01 08:11 UTC, mzeeshanali requested changes

2023-02-01 08:11 UTC, mzeeshanali commented on main.go
> +	file, err := os.Open(os.Args[1])
what if user does not pass filepath?

2023-02-01 08:11 UTC, mzeeshanali commented on main.go
> +	s, _ := json.Marshal(records)
handle error please

2023-02-01 08:12 UTC, Ammar022 commented on main.go
> +	file, err := os.Open(os.Args[1])
It will return error I have checked this condition.

2023-02-01 08:12 UTC, mzeeshanali requested changes
Update your `PR` title please

2023-02-01 08:13 UTC, Ammar022 commented on main.go
> +	s, _ := json.Marshal(records)
Done.

2023-02-01 08:14 UTC, mzeeshanali commented on main.go
> +	file, err := os.Open(os.Args[1])
what error it will return? what if args length is less than two?

2023-02-01 08:31 UTC, mzeeshanali requested changes

2023-02-01 08:31 UTC, mzeeshanali commented on main.go
> +	}
what if in future we want to get one additional argument along with filepath?

2023-02-01 08:31 UTC, mzeeshanali commented on main.go
> +		fmt.Println("Failed to convert Data in Jason:", err)
```suggestion
		fmt.Println("Failed to marshal data into json:", err)
```

2023-02-01 11:44 UTC, mzeeshanali requested changes

2023-02-01 11:44 UTC, mzeeshanali commented on data2.csv
> +heelo, world,24
add empty line

2023-02-01 11:44 UTC, mzeeshanali commented on main.go
> +			fmt.Println("Failed to marshal Data in Jason:", err)
```suggestion
			fmt.Println("Failed to marshal data in json:", err)
```

2023-02-01 11:44 UTC, mzeeshanali commented on main.go
> +			os.Exit(1)
why `os.Exit(1)` here?

2023-02-02 05:52 UTC, mzeeshanali approved these changes

2023-02-02 05:55 UTC, merged